# Generated by gallery/generate.py; do not edit.
function pipez_gallery:clear
fill 190 98 190 246 98 250 minecraft:stone
scoreboard players set #anchors pipez_gallery 0
setblock 196 101 224 minecraft:barrel
setblock 196 102 235 minecraft:barrel
setblock 196 103 236 minecraft:barrel
setblock 197 102 236 minecraft:barrel
setblock 204 103 224 minecraft:barrel
setblock 212 102 223 minecraft:barrel
setblock 220 102 225 minecraft:barrel
setblock 227 102 224 minecraft:barrel
setblock 237 102 224 minecraft:barrel
setblock 196 100 196 pipez:item_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 202 100 196 pipez:fluid_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 208 100 196 pipez:energy_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 214 100 196 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 220 100 196 pipez:gas_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 196 100 204 pipez:item_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 196 100 205 pipez:item_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 196 100 206 pipez:item_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 202 100 204 pipez:fluid_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 202 100 205 pipez:fluid_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 202 100 206 pipez:fluid_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 208 100 204 pipez:energy_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 208 100 205 pipez:energy_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 208 100 206 pipez:energy_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 214 100 204 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 214 100 205 pipez:universal_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 214 100 206 pipez:universal_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 220 100 204 pipez:gas_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 220 100 205 pipez:gas_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 220 100 206 pipez:gas_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 232 102 210 pipez:universal_pipe[down=true,east=true,has_data=false,north=true,south=true,up=true,waterlogged=false,west=true]
scoreboard players add #anchors pipez_gallery 1
setblock 232 101 210 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=false,up=true,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 232 103 210 pipez:universal_pipe[down=true,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 232 102 209 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 232 102 211 pipez:universal_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 231 102 210 pipez:universal_pipe[down=false,east=true,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false]
scoreboard players add #anchors pipez_gallery 1
setblock 233 102 210 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=true]
scoreboard players add #anchors pipez_gallery 1
setblock 196 102 224 pipez:item_pipe[down=true,east=false,has_data=true,north=false,south=false,up=false,waterlogged=false,west=false]
data merge block 196 102 224 {ExtractingSides:[1b,0b,0b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]}
scoreboard players add #anchors pipez_gallery 1
setblock 204 102 224 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=false,up=true,waterlogged=false,west=false]
data merge block 204 102 224 {ExtractingSides:[0b,1b,0b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]}
scoreboard players add #anchors pipez_gallery 1
setblock 212 102 224 pipez:item_pipe[down=false,east=false,has_data=true,north=true,south=false,up=false,waterlogged=false,west=false]
data merge block 212 102 224 {ExtractingSides:[0b,0b,1b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]}
scoreboard players add #anchors pipez_gallery 1
setblock 220 102 224 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=true,up=false,waterlogged=false,west=false]
data merge block 220 102 224 {ExtractingSides:[0b,0b,0b,1b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]}
scoreboard players add #anchors pipez_gallery 1
setblock 228 102 224 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=false,up=false,waterlogged=false,west=true]
data merge block 228 102 224 {ExtractingSides:[0b,0b,0b,0b,1b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]}
scoreboard players add #anchors pipez_gallery 1
setblock 236 102 224 pipez:item_pipe[down=false,east=true,has_data=true,north=false,south=false,up=false,waterlogged=false,west=false]
data merge block 236 102 224 {ExtractingSides:[0b,0b,0b,0b,0b,1b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]}
scoreboard players add #anchors pipez_gallery 1
setblock 196 102 236 pipez:universal_pipe[down=false,east=true,has_data=true,north=true,south=false,up=true,waterlogged=false,west=false]
data merge block 196 102 236 {ExtractingSides:[0b,1b,1b,0b,0b,1b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]}
scoreboard players add #anchors pipez_gallery 1
setblock 210 102 236 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=false,up=false,waterlogged=false,west=false]
data merge block 210 102 236 {ExtractingSides:[0b,0b,0b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,1b]}
scoreboard players add #anchors pipez_gallery 1
setblock 211 102 236 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=false,up=false,waterlogged=false,west=false]
data merge block 211 102 236 {ExtractingSides:[0b,0b,0b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,1b,0b]}
scoreboard players add #anchors pipez_gallery 1
setblock 224 102 236 minecraft:water
setblock 224 102 236 pipez:item_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=true,west=false]
scoreboard players add #anchors pipez_gallery 1
# Reassert exact states after all neighbor updates and NBT writes.
setblock 196 100 196 pipez:item_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false]
setblock 202 100 196 pipez:fluid_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false]
setblock 208 100 196 pipez:energy_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false]
setblock 214 100 196 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false]
setblock 220 100 196 pipez:gas_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false]
setblock 196 100 204 pipez:item_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false]
setblock 196 100 205 pipez:item_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false]
setblock 196 100 206 pipez:item_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false]
setblock 202 100 204 pipez:fluid_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false]
setblock 202 100 205 pipez:fluid_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false]
setblock 202 100 206 pipez:fluid_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false]
setblock 208 100 204 pipez:energy_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false]
setblock 208 100 205 pipez:energy_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false]
setblock 208 100 206 pipez:energy_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false]
setblock 214 100 204 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false]
setblock 214 100 205 pipez:universal_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false]
setblock 214 100 206 pipez:universal_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false]
setblock 220 100 204 pipez:gas_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false]
setblock 220 100 205 pipez:gas_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false]
setblock 220 100 206 pipez:gas_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false]
setblock 232 102 210 pipez:universal_pipe[down=true,east=true,has_data=false,north=true,south=true,up=true,waterlogged=false,west=true]
setblock 232 101 210 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=false,up=true,waterlogged=false,west=false]
setblock 232 103 210 pipez:universal_pipe[down=true,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false]
setblock 232 102 209 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false]
setblock 232 102 211 pipez:universal_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false]
setblock 231 102 210 pipez:universal_pipe[down=false,east=true,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false]
setblock 233 102 210 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=true]
setblock 196 102 224 pipez:item_pipe[down=true,east=false,has_data=true,north=false,south=false,up=false,waterlogged=false,west=false]
data merge block 196 102 224 {ExtractingSides:[1b,0b,0b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]}
setblock 204 102 224 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=false,up=true,waterlogged=false,west=false]
data merge block 204 102 224 {ExtractingSides:[0b,1b,0b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]}
setblock 212 102 224 pipez:item_pipe[down=false,east=false,has_data=true,north=true,south=false,up=false,waterlogged=false,west=false]
data merge block 212 102 224 {ExtractingSides:[0b,0b,1b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]}
setblock 220 102 224 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=true,up=false,waterlogged=false,west=false]
data merge block 220 102 224 {ExtractingSides:[0b,0b,0b,1b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]}
setblock 228 102 224 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=false,up=false,waterlogged=false,west=true]
data merge block 228 102 224 {ExtractingSides:[0b,0b,0b,0b,1b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]}
setblock 236 102 224 pipez:item_pipe[down=false,east=true,has_data=true,north=false,south=false,up=false,waterlogged=false,west=false]
data merge block 236 102 224 {ExtractingSides:[0b,0b,0b,0b,0b,1b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]}
setblock 196 102 236 pipez:universal_pipe[down=false,east=true,has_data=true,north=true,south=false,up=true,waterlogged=false,west=false]
data merge block 196 102 236 {ExtractingSides:[0b,1b,1b,0b,0b,1b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]}
setblock 210 102 236 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=false,up=false,waterlogged=false,west=false]
data merge block 210 102 236 {ExtractingSides:[0b,0b,0b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,1b]}
setblock 211 102 236 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=false,up=false,waterlogged=false,west=false]
data merge block 211 102 236 {ExtractingSides:[0b,0b,0b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,1b,0b]}
setblock 224 102 236 pipez:item_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=true,west=false]
function pipez_gallery:verify
tellraw @a [{"text":"Pipez gallery built: "},{"score":{"name":"#anchors","objective":"pipez_gallery"}},{"text":" anchors, "},{"score":{"name":"#failures","objective":"pipez_gallery"}},{"text":" verification failures"}]
