# Generated by gallery/generate.py; do not edit.
scoreboard players set #failures pipez_gallery 0
scoreboard players set #checked pipez_gallery 0
execute unless block 196 100 196 pipez:item_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 202 100 196 pipez:fluid_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 208 100 196 pipez:energy_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 214 100 196 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 220 100 196 pipez:gas_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 196 100 204 pipez:item_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 196 100 205 pipez:item_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 196 100 206 pipez:item_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 202 100 204 pipez:fluid_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 202 100 205 pipez:fluid_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 202 100 206 pipez:fluid_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 208 100 204 pipez:energy_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 208 100 205 pipez:energy_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 208 100 206 pipez:energy_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 214 100 204 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 214 100 205 pipez:universal_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 214 100 206 pipez:universal_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 220 100 204 pipez:gas_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 220 100 205 pipez:gas_pipe[down=false,east=false,has_data=false,north=true,south=true,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 220 100 206 pipez:gas_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 232 102 210 pipez:universal_pipe[down=true,east=true,has_data=false,north=true,south=true,up=true,waterlogged=false,west=true] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 232 101 210 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=false,up=true,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 232 103 210 pipez:universal_pipe[down=true,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 232 102 209 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=true,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 232 102 211 pipez:universal_pipe[down=false,east=false,has_data=false,north=true,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 231 102 210 pipez:universal_pipe[down=false,east=true,has_data=false,north=false,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 233 102 210 pipez:universal_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=false,west=true] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 196 102 224 pipez:item_pipe[down=true,east=false,has_data=true,north=false,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
execute unless data block 196 102 224 {id:"pipez:item_pipe"} run scoreboard players add #failures pipez_gallery 1
execute unless data block 196 102 224 {ExtractingSides:[1b,0b,0b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]} run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 204 102 224 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=false,up=true,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
execute unless data block 204 102 224 {id:"pipez:item_pipe"} run scoreboard players add #failures pipez_gallery 1
execute unless data block 204 102 224 {ExtractingSides:[0b,1b,0b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]} run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 212 102 224 pipez:item_pipe[down=false,east=false,has_data=true,north=true,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
execute unless data block 212 102 224 {id:"pipez:item_pipe"} run scoreboard players add #failures pipez_gallery 1
execute unless data block 212 102 224 {ExtractingSides:[0b,0b,1b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]} run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 220 102 224 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=true,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
execute unless data block 220 102 224 {id:"pipez:item_pipe"} run scoreboard players add #failures pipez_gallery 1
execute unless data block 220 102 224 {ExtractingSides:[0b,0b,0b,1b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]} run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 228 102 224 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=false,up=false,waterlogged=false,west=true] run scoreboard players add #failures pipez_gallery 1
execute unless data block 228 102 224 {id:"pipez:item_pipe"} run scoreboard players add #failures pipez_gallery 1
execute unless data block 228 102 224 {ExtractingSides:[0b,0b,0b,0b,1b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]} run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 236 102 224 pipez:item_pipe[down=false,east=true,has_data=true,north=false,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
execute unless data block 236 102 224 {id:"pipez:item_pipe"} run scoreboard players add #failures pipez_gallery 1
execute unless data block 236 102 224 {ExtractingSides:[0b,0b,0b,0b,0b,1b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]} run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 196 102 236 pipez:universal_pipe[down=false,east=true,has_data=true,north=true,south=false,up=true,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
execute unless data block 196 102 236 {id:"pipez:universal_pipe"} run scoreboard players add #failures pipez_gallery 1
execute unless data block 196 102 236 {ExtractingSides:[0b,1b,1b,0b,0b,1b],DisconnectedSides:[0b,0b,0b,0b,0b,0b]} run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 210 102 236 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
execute unless data block 210 102 236 {id:"pipez:item_pipe"} run scoreboard players add #failures pipez_gallery 1
execute unless data block 210 102 236 {ExtractingSides:[0b,0b,0b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,0b,1b]} run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 211 102 236 pipez:item_pipe[down=false,east=false,has_data=true,north=false,south=false,up=false,waterlogged=false,west=false] run scoreboard players add #failures pipez_gallery 1
execute unless data block 211 102 236 {id:"pipez:item_pipe"} run scoreboard players add #failures pipez_gallery 1
execute unless data block 211 102 236 {ExtractingSides:[0b,0b,0b,0b,0b,0b],DisconnectedSides:[0b,0b,0b,0b,1b,0b]} run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless block 224 102 236 pipez:item_pipe[down=false,east=false,has_data=false,north=false,south=false,up=false,waterlogged=true,west=false] run scoreboard players add #failures pipez_gallery 1
scoreboard players add #checked pipez_gallery 1
execute unless score #checked pipez_gallery matches 37 run scoreboard players add #failures pipez_gallery 1
