org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-pipez
addon_name=BlueMap Pipez Add-on
addon_version=0.1.0-alpha.3
addon_group=io.github.jan-guenter
artifact_id=bluemap-pipez-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
